notify_audit: false
locked: false
name: '[${environment}] ELB returning high number of 5xx errors'
tags: ['${environment}', reactiveops]
include_tags: false
no_data_timeframe: null
silenced: {}
require_full_window: true
new_host_delay: 300
notify_no_data: false
renotify_interval: 0
escalation_message: ''
query: "min(last_15m):100 * avg:aws.elb.httpcode_backend_5xx{kubernetescluster:${cluster}} by {loadbalancername}.as_rate().fill(zero) / avg:aws.elb.request_count{kubernetescluster:${cluster}} by {loadbalancername}.as_rate().fill(zero) >= 2"
message: |
  {{#is_alert}}
  The {{kubernetes.io/service-name}} ELB is reporting the Kubernetes Service is returning more 5xx errors than normal
  {{/is_alert}}
  {{^is_alert}}
  The ELB is no longer returning 5xx errors
  {{/is_alert}}
  ${notifications}
type: query alert
thresholds: {critical: 2}
timeout_h: 0
